Feature/feature branch
LuisHernandezCoding/Tik-Tak-Toe pull request #4
Opened 2022-10-10 21:15 UTC by LuisHernandezCoding

2022-10-12 21:52 UTC, mricanho requested changes
Hi    ###Luis, 

Good job so far! 🔥🔥

Overall it's a good first attempt, the game is a little bit buggy, and some loops are creating these errors, double-check that.

Good work on the use of rubocop and the RSpec, nothing more to do there.
There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️

_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-12 21:52 UTC, mricanho commented on README.md
> +## Table of contents
You can delete this section

2022-10-12 21:52 UTC, mricanho commented on README.md
> +git clone https://github.com/LuisHernandezCoding/tic_tac_toe
This link is broken

2022-10-12 21:52 UTC, mricanho commented on lib/ui.rb
> +  # rubocop:enable Style/Semicolon
Check a way to work around this, try an if statement or other option, this is not the ruby way

2022-10-12 21:52 UTC, mricanho commented on lib/ui.rb
> +    end
This while loop creates a little bug, use a if statement instead

2022-10-12 21:56 UTC, mricanho commented
https://www.loom.com/share/d642488a57864c5fb351bdef3981d01d

2022-10-12 22:38 UTC, LuisHernandezCoding commented on README.md
> +## Table of contents
Thanks a lot! its deleted on commit 528723d

2022-10-12 22:38 UTC, LuisHernandezCoding commented on README.md
> +git clone https://github.com/LuisHernandezCoding/tic_tac_toe
fixed now on commit 528723d

2022-10-12 22:40 UTC, LuisHernandezCoding commented on lib/ui.rb
> +  # rubocop:enable Style/Semicolon
cool, changed to regular if statement instead of ternary

2022-10-12 22:40 UTC, LuisHernandezCoding commented on lib/ui.rb
> +  # rubocop:enable Style/Semicolon
sorry, in commit 528723d

2022-10-12 22:40 UTC, LuisHernandezCoding commented on lib/ui.rb
> +    end
changed to an if statement in 528723d

2022-10-13 13:37 UTC, mricanho approved these changes
# Status: ✔️ Project Approved ✔️ 

Hello Luis! 🔥 

You worked hard in all the instructions that I give you👍🏽 

Now you can merge this branch 🚀 

### 💻 👩🏽‍💻  Happy Coding!  👨🏽‍💻 🖥️

2022-10-13 13:47 UTC, merged